[package]
name = "fake-yield"
version = "0.1.0"
authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
edition = "2018"

[dependencies]
itertools = "*"
proc-macro-hack = "0.5"
fake-yield-inner = { version = "*", path = "./inner/" }
